// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Template/image_frame_data.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Template/image_frame_data.proto</summary>
public static partial class ImageFrameDataReflection {

  #region Descriptor
  /// <summary>File descriptor for Template/image_frame_data.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ImageFrameDataReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Ch9UZW1wbGF0ZS9pbWFnZV9mcmFtZV9kYXRhLnByb3RvImcKDkltYWdlRnJh",
          "bWVEYXRhEgoKAnRzGAEgASgDEg0KBXdpZHRoGAIgASgFEg4KBmhlaWdodBgD",
          "IAEoBRINCgVpbWFnZRgEIAMoDBILCgNjbWQYBSABKAUSDgoGcGFyYW1zGAYg",
          "ASgJ"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::ImageFrameData), global::ImageFrameData.Parser, new[]{ "Ts", "Width", "Height", "Image", "Cmd", "Params" }, null, null, null, null)
        }));
  }
  #endregion

}
#region Messages
[global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
public sealed partial class ImageFrameData : pb::IMessage<ImageFrameData>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    , pb::IBufferMessage
#endif
{
  private static readonly pb::MessageParser<ImageFrameData> _parser = new pb::MessageParser<ImageFrameData>(() => new ImageFrameData());
  private pb::UnknownFieldSet _unknownFields;
  private int _hasBits0;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pb::MessageParser<ImageFrameData> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::ImageFrameDataReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ImageFrameData() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ImageFrameData(ImageFrameData other) : this() {
    _hasBits0 = other._hasBits0;
    ts_ = other.ts_;
    width_ = other.width_;
    height_ = other.height_;
    image_ = other.image_.Clone();
    cmd_ = other.cmd_;
    params_ = other.params_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public ImageFrameData Clone() {
    return new ImageFrameData(this);
  }

  /// <summary>Field number for the "ts" field.</summary>
  public const int TsFieldNumber = 1;
  private readonly static long TsDefaultValue = 0L;

  private long ts_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public long Ts {
    get { if ((_hasBits0 & 1) != 0) { return ts_; } else { return TsDefaultValue; } }
    set {
      _hasBits0 |= 1;
      ts_ = value;
    }
  }
  /// <summary>Gets whether the "ts" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasTs {
    get { return (_hasBits0 & 1) != 0; }
  }
  /// <summary>Clears the value of the "ts" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearTs() {
    _hasBits0 &= ~1;
  }

  /// <summary>Field number for the "width" field.</summary>
  public const int WidthFieldNumber = 2;
  private readonly static int WidthDefaultValue = 0;

  private int width_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Width {
    get { if ((_hasBits0 & 2) != 0) { return width_; } else { return WidthDefaultValue; } }
    set {
      _hasBits0 |= 2;
      width_ = value;
    }
  }
  /// <summary>Gets whether the "width" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasWidth {
    get { return (_hasBits0 & 2) != 0; }
  }
  /// <summary>Clears the value of the "width" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearWidth() {
    _hasBits0 &= ~2;
  }

  /// <summary>Field number for the "height" field.</summary>
  public const int HeightFieldNumber = 3;
  private readonly static int HeightDefaultValue = 0;

  private int height_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Height {
    get { if ((_hasBits0 & 4) != 0) { return height_; } else { return HeightDefaultValue; } }
    set {
      _hasBits0 |= 4;
      height_ = value;
    }
  }
  /// <summary>Gets whether the "height" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasHeight {
    get { return (_hasBits0 & 4) != 0; }
  }
  /// <summary>Clears the value of the "height" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearHeight() {
    _hasBits0 &= ~4;
  }

  /// <summary>Field number for the "image" field.</summary>
  public const int ImageFieldNumber = 4;
  private static readonly pb::FieldCodec<pb::ByteString> _repeated_image_codec
      = pb::FieldCodec.ForBytes(34);
  private readonly pbc::RepeatedField<pb::ByteString> image_ = new pbc::RepeatedField<pb::ByteString>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public pbc::RepeatedField<pb::ByteString> Image {
    get { return image_; }
  }

  /// <summary>Field number for the "cmd" field.</summary>
  public const int CmdFieldNumber = 5;
  private readonly static int CmdDefaultValue = 0;

  private int cmd_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int Cmd {
    get { if ((_hasBits0 & 8) != 0) { return cmd_; } else { return CmdDefaultValue; } }
    set {
      _hasBits0 |= 8;
      cmd_ = value;
    }
  }
  /// <summary>Gets whether the "cmd" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasCmd {
    get { return (_hasBits0 & 8) != 0; }
  }
  /// <summary>Clears the value of the "cmd" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearCmd() {
    _hasBits0 &= ~8;
  }

  /// <summary>Field number for the "params" field.</summary>
  public const int ParamsFieldNumber = 6;
  private readonly static string ParamsDefaultValue = "";

  private string params_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public string Params {
    get { return params_ ?? ParamsDefaultValue; }
    set {
      params_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }
  /// <summary>Gets whether the "params" field is set</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool HasParams {
    get { return params_ != null; }
  }
  /// <summary>Clears the value of the "params" field</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void ClearParams() {
    params_ = null;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override bool Equals(object other) {
    return Equals(other as ImageFrameData);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public bool Equals(ImageFrameData other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Ts != other.Ts) return false;
    if (Width != other.Width) return false;
    if (Height != other.Height) return false;
    if(!image_.Equals(other.image_)) return false;
    if (Cmd != other.Cmd) return false;
    if (Params != other.Params) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override int GetHashCode() {
    int hash = 1;
    if (HasTs) hash ^= Ts.GetHashCode();
    if (HasWidth) hash ^= Width.GetHashCode();
    if (HasHeight) hash ^= Height.GetHashCode();
    hash ^= image_.GetHashCode();
    if (HasCmd) hash ^= Cmd.GetHashCode();
    if (HasParams) hash ^= Params.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void WriteTo(pb::CodedOutputStream output) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    output.WriteRawMessage(this);
  #else
    if (HasTs) {
      output.WriteRawTag(8);
      output.WriteInt64(Ts);
    }
    if (HasWidth) {
      output.WriteRawTag(16);
      output.WriteInt32(Width);
    }
    if (HasHeight) {
      output.WriteRawTag(24);
      output.WriteInt32(Height);
    }
    image_.WriteTo(output, _repeated_image_codec);
    if (HasCmd) {
      output.WriteRawTag(40);
      output.WriteInt32(Cmd);
    }
    if (HasParams) {
      output.WriteRawTag(50);
      output.WriteString(Params);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
    if (HasTs) {
      output.WriteRawTag(8);
      output.WriteInt64(Ts);
    }
    if (HasWidth) {
      output.WriteRawTag(16);
      output.WriteInt32(Width);
    }
    if (HasHeight) {
      output.WriteRawTag(24);
      output.WriteInt32(Height);
    }
    image_.WriteTo(ref output, _repeated_image_codec);
    if (HasCmd) {
      output.WriteRawTag(40);
      output.WriteInt32(Cmd);
    }
    if (HasParams) {
      output.WriteRawTag(50);
      output.WriteString(Params);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(ref output);
    }
  }
  #endif

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public int CalculateSize() {
    int size = 0;
    if (HasTs) {
      size += 1 + pb::CodedOutputStream.ComputeInt64Size(Ts);
    }
    if (HasWidth) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Width);
    }
    if (HasHeight) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Height);
    }
    size += image_.CalculateSize(_repeated_image_codec);
    if (HasCmd) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Cmd);
    }
    if (HasParams) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Params);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(ImageFrameData other) {
    if (other == null) {
      return;
    }
    if (other.HasTs) {
      Ts = other.Ts;
    }
    if (other.HasWidth) {
      Width = other.Width;
    }
    if (other.HasHeight) {
      Height = other.Height;
    }
    image_.Add(other.image_);
    if (other.HasCmd) {
      Cmd = other.Cmd;
    }
    if (other.HasParams) {
      Params = other.Params;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  public void MergeFrom(pb::CodedInputStream input) {
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    input.ReadRawMessage(this);
  #else
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          Ts = input.ReadInt64();
          break;
        }
        case 16: {
          Width = input.ReadInt32();
          break;
        }
        case 24: {
          Height = input.ReadInt32();
          break;
        }
        case 34: {
          image_.AddEntriesFrom(input, _repeated_image_codec);
          break;
        }
        case 40: {
          Cmd = input.ReadInt32();
          break;
        }
        case 50: {
          Params = input.ReadString();
          break;
        }
      }
    }
  #endif
  }

  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
  void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
          break;
        case 8: {
          Ts = input.ReadInt64();
          break;
        }
        case 16: {
          Width = input.ReadInt32();
          break;
        }
        case 24: {
          Height = input.ReadInt32();
          break;
        }
        case 34: {
          image_.AddEntriesFrom(ref input, _repeated_image_codec);
          break;
        }
        case 40: {
          Cmd = input.ReadInt32();
          break;
        }
        case 50: {
          Params = input.ReadString();
          break;
        }
      }
    }
  }
  #endif

}

#endregion


#endregion Designer generated code
